### ISSUE TITLE
Need alternative to !! that works with hawk

### ISSUE THREAD

**Issue by codygman** [gelisam/hawk#162]
I was going through this [presentation on hawk]() and this example came up:

```
cat /etc/passwd | hawk -d: -o'\t' -m '\l -> (l !! 0,l !! 2)'
```

This worked just fine on my Linux laptop and I finished the rest of the presentation. Later I was showing a friend on a Mac hawk and pasted that example into terminal only to see an index error :cold_sweat: 

The reason being that a BSD /etc/passwd file looks like this:

```
# There are leading
# comment headers
# like this
root:!:0:0::/:/usr/bin/ksh
daemon:!:1:1::/etc:
bin:!:2:2::/bin:
sys:!:3:3::/usr/sys: 
adm:!:4:4::/var/adm:
uucp:!:5:5::/usr/lib/uucp: 
guest:!:100:100::/home/guest:
nobody:!:4294967294:4294967294::/:
```

For those first 3 lines the indexing will fail. I got around it at the time by doing something like this:

```
tail /etc/passwd | hawk -d: -o'\t' -m '\l -> (l !! 0,l !! 2)'
```

If it weren't just an example though I would have had to figure out the correct offset to list all users.

Any ideas?

**Comment by mitchellwrosen** [comment]
I solve this in [h](https://github.com/mitchellwrosen/h) by treating thrown exceptions as an indication to ignore this line.

So, if you want to match on non-comment lines, just pass a partial function (using `MultiWayIf` syntax):

```
$ cat /etc/passwd | h '\x -> if | not (T.isPrefixOf "#" xs) -> let ys = T.splitOn ":" xs in ys !! 0 <> " " <> ys !! 2'
root 0
daemon 1
bin 2
sys 3
adm 4
uucp 5
guest 100
nobody 4294967294
```

Note there is no case for when `T.isPrefixOf "#" xs` is true.

**Comment by GregorySchwartz** [comment]
@codygman Can't you just import Safe and avoid the partial function with `atMay` instead of `!!`?

**Comment by gelisam** [comment]
Thanks @GregorySchwartz, that sounds like the best solution. Users who care about those things can do that, there is no need for any special support from hawk's side, so I will close this issue.

@mitchellwrosen, I think exceptions are important indicators of bugs and shouldn't be silenced that way, but if you want that behaviour in hawk anyway, I'm open to the possibility of adding a flag which provides that behaviour. If that's what you want (though you probably prefer to use `h` than `hawk`, so probably not), please file a separate issue.
