### ISSUE TITLE
use filelock

### ISSUE THREAD

**Issue by gelisam** [gelisam/hawk#172]
We define our own locking system based on ports; better reuse an existing implementation based on files: http://hackage.haskell.org/package/filelock

**Comment by gelisam** [comment]
This is more important than ever as it seems like the existing socket-based locking system is no longer working:

    $ hawk [1..10] | hawk -a 'L.reverse'
    hawk: Network.Socket.bind: resource busy (Address already in use)

**Comment by Rahel-A** [comment]
https://github.com/lars-olsson/hawk/tree/%23172-use-filelock
I believe I've addressed that issue. In this branch I'm doing the following:
Use a common file to prevent other parallel hawk processes from running, until the current one finishes. The filelock library will hold the blocked processes until it's available.
The common file is deleted after the current process is finished running the critical IO action.

**Comment by gelisam** [comment]
Sounds good, can you send a pull request?

**Comment by gelisam** [comment]
Implemented by #178
