### ISSUE TITLE
hawk: /home/dir/.hawk/lock.tmp: No such file or directory

### ISSUE THREAD

**Issue by juhp** [gelisam/hawk#213]
I am not sure what it is going on but when I try to use hawk in a new system after a long break I got:

```
$ hawk '[1..3]'
hawk: /home/dir/.hawk/lock.tmp: openFd: does not exist (No such file or directory)
```

Just for transparency this is running in a Fedora Toolbox user container, but I don't _think_ that should matter.

**Comment by juhp** [comment]
Workaround is just to create `~/.hawk/` manually.

**Comment by gelisam** [comment]
Hmm, `hawk` is supposed to create that folder for you if it doesn't exist. I am guessing that the locking mechanism is now being activated too early, before we got a chance to create the folder.

**Comment by gelisam** [comment]
Indeed, that was a regression introduced by #172, which switched the locking mechanism from a socket-based to a file-based approach. We've always been activating the lock before creating the folder, but that used not to be a problem.

**Comment by juhp** [comment]
Thanks, looks good now :+1:
