### ISSUE TITLE
ghc not found

### ISSUE THREAD

**Issue by gelisam** [gelisam/hawk#235]
From #228 : 

> I just installed Stack on my Macbook for the purpose of installing Hawk, and stack install ran to completion.
> 
> [...]
> 
> Now I get the new error:
> 
> $ hawk '[1..3]'
> hawk: ghc: readCreateProcessWithExitCode: runInteractiveProcess: exec: does not exist (No such file or directory)

**Comment by gelisam** [comment]
CC @osfameron

**Comment by gelisam** [comment]
The error says that the `ghc` executable, which is used for compiling Haskell code, is not in one of the folders listed in your PATH environment variable. That makes sense, since `stack` intentionally installs `ghc` in a private folder which does not affect your global installation of `ghc` if any. Since I do have a global installation of `ghc`, I did not encounter that problem; so one easy workaround would be to also install ghc globally, using [ghcup](https://www.haskell.org/ghcup/) for example.

**Comment by gelisam** [comment]
The above is a workaround, but I still want to fix the underlying bug. The ghc executable is probably used to compile the hawk prelude, while stack's private installation of hint and ghc are used to interpret the command-line expression. That's bad, because those might not be the same version of ghc, in which case the compiled version of the prelude will not be used. That might explain #126, in which I found that compiling the hawk prelude did not lead to the expected speedup?

**Comment by osfameron** [comment]
Hah, yeah, that makes sense.
So, as a workaround, I created `~/.local/bin/ghc` as:

```
#!/bin/bash
stack ghc -- $*
```

which at least gets `hawk '1'` to run, and might help debug the prelude compilation issue...
But obviously that's not a nice solution 😁.

**Comment by gelisam** [comment]
Closing in favour of #246
